install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

skip_tags: true

image: Visual Studio 2017

configuration: Release

environment:
  VisualStudioVersion: 15.0

before_build:
  - ps: .\init.ps1
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: src\GitLink.sln
  parallel: true
  verbosity: minimal

artifacts:
- path: '**\bin\**\*.nupkg'
  name: NuGet Package
